### ISSUE TITLE
rosette experiment is blank

### ISSUE THREAD

**Issue by dschneiderch** [Gregor-Mendel-Institute/aradeepopsis#55]
This looks like a neat feature but i couldn't see anything..... I noticed that the `file` column doesn't include the extension. is that an issue?

here is how i processed the traits file to include the relevant info. (sorry not reproducible)
```
library(tidyverse)
library(here)
library(glue)
treatment_map = read_csv(here('data','treatment_map.csv'))
data = read_csv(here('output',paste0('deeposis',params$model),'aradeepopsis_traits.csv'))
plantarea <- 
  data %>%
  separate(file, into = c('plantbarcode','exp','datetime','camera','frame'), sep='-', remove = F) %>% 
  mutate(datetime = parse_datetime(datetime),
         date = as.Date(datetime))
plantarea <- plantarea %>% full_join(treatment_map) %>% 
  mutate(treatment_cut = cut_width(treatment, 10))

write_csv(plantarea, here('output',paste0('deeposis', params$model),'aradeepopsis_traits_date.csv'))
```

![image](https://user-images.githubusercontent.com/7461221/103839879-31004980-5045-11eb-8c53-e50dabce73f5.png)

Also, small note, contrary to the popup directions it doesn't appear the file needs the timestamp format as a column

**Comment by phue** [comment]
To clarify: the values `file` column in the table you upload have to match the `file` column in `aradeepopsis_traits.csv` (which in you case seems to be `plantbarcode`)

I believe the reason why the plot is blank is a bug I fixed a few month ago (in https://github.com/Gregor-Mendel-Institute/aradeepopsis/commit/8a38c825b3c86a3f261bf4dc8dd3565e94b6f484) but I never pushed a release after that (sorry)
It should work with the `dev` branch though

> Also, small note, contrary to the popup directions it doesn't appear the file needs the timestamp format as a column
You're right, I should improve the wording there

**Comment by dschneiderch** [comment]
can I run just the docker shiny from `dev` branch or do I need to rerun the nextflow analysis?

**Comment by dschneiderch** [comment]
I tried the dev docker image and still get the same error when I run
`docker run -v $(pwd):/mnt/shiny -p 44333:44333 beckerlab/aradeepopsis-shiny:dev R -e "shiny::runApp('/mnt/shiny/app.R', port=44333, host='0.0.0.0')"`

**Comment by phue** [comment]
> can I run just the docker shiny from `dev` branch or do I need to rerun the nextflow analysis?

No it will probably start from the beginning if you do that.

But you can just put the [app.R](https://github.com/Gregor-Mendel-Institute/aradeepopsis/blob/dev/assets/shiny/app.R) in your results folder and it should work.

**Comment by phue** [comment]
> I tried the dev docker image and still get the same error when I run
> `docker run -v $(pwd):/mnt/shiny -p 44333:44333 beckerlab/aradeepopsis-shiny:dev R -e "shiny::runApp('/mnt/shiny/app.R', port=44333, host='0.0.0.0')"`

That is expected, because the app.R is not in the docker image but in the pipeline repository. So it is still using the old one

**Comment by dschneiderch** [comment]
this is fixed so closing because it's continued in #54
